/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* USER CODE BEGIN Includes */
#include "aprs_bits.h"
#include <string.h>
/* USER CODE END Includes */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

#define SAMPLE_RATE       19200
#define BAUD              1200
#define SAMPLES_PER_BIT   (SAMPLE_RATE / BAUD)   /* = 16, exact integer */

#define MAX_BITS          1000
#define AUDIO_BUFFER_SIZE 512

#define DAC_MID           2048
#define DAC_AMPLITUDE     1800

/*
 * 32-bit phase accumulator increments.
 * Formula: inc = freq / Fs * 2^32
 *
 * MARK  (1200 Hz): 1200 / 19200 * 2^32 = 268435456
 * SPACE (2200 Hz): 2200 / 19200 * 2^32 = 491520000
 *
 * Verify: 268435456 / 2^32 * 19200 = 1200.000 Hz  ✓
 *         491520000 / 2^32 * 19200 = 2200.000 Hz  ✓
 */
#define PHASE_INC_MARK    268435456UL
#define PHASE_INC_SPACE   491520000UL

/* USER CODE END PD */

/* Private variables ---------------------------------------------------------*/

/*
 * 256-entry 12-bit sine LUT.
 * Values range 248..3848, centred on 2048, amplitude ~1800 counts.
 * Kept well above 0 and below 4095 to avoid the DAC output buffer dead zones.
 *
 * Generated by: round(2048 + 1800 * sin(2*pi*i/256))  for i in 0..255
 */
/*
 * 256-entry sine LUT centred on 2048, amplitude 1800.
 * Trough = 248, Peak = 3848 — both clear of 12-bit DAC limits.
 * Generated by: round(2048 + 1800 * sin(2*pi*i/256)) for i in 0..255
 */
static const uint16_t SINE_LUT[256] = {
    2048, 2092, 2136, 2180, 2224, 2268, 2312, 2356,
    2399, 2442, 2485, 2528, 2571, 2613, 2654, 2696,
    2737, 2777, 2818, 2857, 2897, 2935, 2973, 3011,
    3048, 3084, 3120, 3155, 3190, 3224, 3257, 3289,
    3321, 3352, 3382, 3411, 3439, 3467, 3494, 3520,
    3545, 3569, 3592, 3614, 3635, 3656, 3675, 3694,
    3711, 3727, 3743, 3757, 3770, 3783, 3794, 3804,
    3813, 3821, 3829, 3834, 3839, 3843, 3846, 3847,
    3848, 3847, 3846, 3843, 3839, 3834, 3829, 3821,
    3813, 3804, 3794, 3783, 3770, 3757, 3743, 3727,
    3711, 3694, 3675, 3656, 3635, 3614, 3592, 3569,
    3545, 3520, 3494, 3467, 3439, 3411, 3382, 3352,
    3321, 3289, 3257, 3224, 3190, 3155, 3120, 3084,
    3048, 3011, 2973, 2935, 2897, 2857, 2818, 2777,
    2737, 2696, 2654, 2613, 2571, 2528, 2485, 2442,
    2399, 2356, 2312, 2268, 2224, 2180, 2136, 2092,
    2048, 2004, 1960, 1916, 1872, 1828, 1784, 1740,
    1697, 1654, 1611, 1568, 1525, 1483, 1442, 1400,
    1359, 1319, 1278, 1239, 1199, 1161, 1123, 1085,
    1048, 1012,  976,  941,  906,  872,  839,  807,
     775,  744,  714,  685,  657,  629,  602,  576,
     551,  527,  504,  482,  461,  440,  421,  402,
     385,  369,  353,  339,  326,  313,  302,  292,
     283,  275,  267,  262,  257,  253,  250,  249,
     248,  249,  250,  253,  257,  262,  267,  275,
     283,  292,  302,  313,  326,  339,  353,  369,
     385,  402,  421,  440,  461,  482,  504,  527,
     551,  576,  602,  629,  657,  685,  714,  744,
     775,  807,  839,  872,  906,  941,  976, 1012,
    1048, 1085, 1123, 1161, 1199, 1239, 1278, 1319,
    1359, 1400, 1442, 1483, 1525, 1568, 1611, 1654,
    1697, 1740, 1784, 1828, 1872, 1916, 1960, 2004,
};

ADC_HandleTypeDef hadc;
DAC_HandleTypeDef hdac;
DMA_HandleTypeDef hdma_dac_ch1;
TIM_HandleTypeDef htim6;
UART_HandleTypeDef huart1;
PCD_HandleTypeDef hpcd_USB_FS;

/* USER CODE BEGIN PV */

uint8_t radioConfig[] = "AT+DMOSETGROUP=0,144.3900,144.3900,0000,1,0000\r\n";
uint8_t filterConfig[] = "AT+SETFILTER=0,0,0\r\n";

uint8_t  bitstream[MAX_BITS];
size_t   bit_len = 0;

uint16_t audio_buffer[AUDIO_BUFFER_SIZE];

/* TX state — written in ISR, read in main: must be volatile */
volatile int tx_done   = 0;
volatile int tx_active = 0;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_DAC_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_USB_PCD_Init(void);
static void MX_TIM6_Init(void);
static void MX_ADC_Init(void);

/* USER CODE BEGIN 0 */

/* =========================================================
 * Bit collector — called by aprs_sendPacket()
 * ========================================================= */
void collectBit(uint8_t bit)
{
    if (bit_len < MAX_BITS) {
        bitstream[bit_len++] = bit;
    }
}

/* =========================================================
 * AFSK modem state
 * Uses a 32-bit phase accumulator + 256-entry LUT.
 * No floating point — safe to call from ISR on Cortex-M0.
 * ========================================================= */
typedef struct {
    uint8_t  *bits;
    size_t    bit_len;
    uint32_t  phase;         /* 32-bit accumulator, full 0..2^32 range */
    uint32_t  sample_index;  /* counts samples since TX start */
} afsk_state_t;

static afsk_state_t afsk;

static void afsk_init(uint8_t *bits, size_t len)
{
    afsk.bits         = bits;
    afsk.bit_len      = len;
    afsk.phase        = 0;
    afsk.sample_index = 0;
}

static uint16_t afsk_next_sample(void)
{
    if (tx_done) {
        return DAC_MID;
    }

    /* SAMPLES_PER_BIT = 16 (exact), so integer division is perfect */
    uint32_t bit_index = afsk.sample_index / SAMPLES_PER_BIT;

    if (bit_index >= afsk.bit_len) {
        tx_done = 1;
        return DAC_MID;
    }

    uint32_t phase_inc = afsk.bits[bit_index] ? PHASE_INC_MARK : PHASE_INC_SPACE;

    /* Advance phase — naturally wraps at 2^32, no branch needed */
    afsk.phase += phase_inc;

    /* Top 8 bits index into the 256-entry LUT */
    uint16_t sample = SINE_LUT[afsk.phase >> 24];

    afsk.sample_index++;

    return sample;
}

/* =========================================================
 * Buffer fill — called from DMA callbacks (ISR context)
 * ========================================================= */
static void fill_buffer(uint16_t *buf, size_t len)
{
    if (tx_done) {
        for (size_t i = 0; i < len; i++) {
            buf[i] = DAC_MID;
        }
    } else {
        for (size_t i = 0; i < len; i++) {
            buf[i] = afsk_next_sample();
        }
    }
}

/* =========================================================
 * DMA half-complete: refill first half of buffer
 * ========================================================= */
void HAL_DAC_ConvHalfCpltCallbackCh1(DAC_HandleTypeDef *hdac_cb)
{
    fill_buffer(audio_buffer, AUDIO_BUFFER_SIZE / 2);
}

/* =========================================================
 * DMA complete: refill second half, handle shutdown
 * ========================================================= */
void HAL_DAC_ConvCpltCallbackCh1(DAC_HandleTypeDef *hdac_cb)
{
    /* Always refill second half first so DMA never starves */
    fill_buffer(&audio_buffer[AUDIO_BUFFER_SIZE / 2], AUDIO_BUFFER_SIZE / 2);

    /* Once tx_done and we've drained enough silent buffers, stop */
    if (tx_done && tx_active) {
        static int drain_cycles = 0;
        if (++drain_cycles > 2) {
            HAL_DAC_Stop_DMA(hdac_cb, DAC_CHANNEL_1);
            HAL_TIM_Base_Stop(&htim6);
            tx_active    = 0;
            drain_cycles = 0;
            /* De-assert PTT */
            HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET);
        }
    }
}

/* USER CODE END 0 */

/* =========================================================
 * Application entry point
 * ========================================================= */
int main(void)
{
    /* USER CODE BEGIN 1 */
    /* USER CODE END 1 */

    HAL_Init();

    /* USER CODE BEGIN Init */
    /* USER CODE END Init */

    SystemClock_Config();

    /* USER CODE BEGIN SysInit */
    /* USER CODE END SysInit */

    MX_GPIO_Init();
    MX_DMA_Init();
    MX_DAC_Init();
    MX_USART1_UART_Init();
    MX_USB_PCD_Init();
    MX_TIM6_Init();
    MX_ADC_Init();

    /* USER CODE BEGIN 2 */
    HAL_UART_Transmit(&huart1, radioConfig, strlen((char *)radioConfig), 1000);
    HAL_Delay(1000);
    HAL_UART_Transmit(&huart1, filterConfig, strlen((char *)filterConfig), 1000);
    HAL_Delay(1000);
    /* USER CODE END 2 */

    /* USER CODE BEGIN WHILE */
    while (1)
    {
        /* ---- Build APRS packet ---- */
        bit_len = 0;
        aprs_sendPacket(
            "KR4GAM",
            "APRS",
            "WIDE1-1,WIDE2-1",
            "!4221.39N/07105.71W-Test beacon",
            collectBit
        );

        /* ---- Initialise modem ---- */
        afsk_init(bitstream, bit_len);

        /* ---- Reset TX flags ---- */
        tx_done   = 0;
        tx_active = 1;

        /* Assert PTT — active LOW */
        HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET);

        /* Pre-fill entire buffer before starting DMA so there's no underrun
           on the very first half-complete callback */
        fill_buffer(audio_buffer, AUDIO_BUFFER_SIZE);

        HAL_Delay(200);

        /* Start timer first, then DMA */
        HAL_TIM_Base_Start(&htim6);
        HAL_DAC_Start_DMA(
            &hdac,
            DAC_CHANNEL_1,
            (uint32_t *)audio_buffer,
            AUDIO_BUFFER_SIZE,
            DAC_ALIGN_12B_R
        );

        /* Spin until DMA callback clears tx_active */
        while (tx_active) { /* idle */ }

        /* Wait 60 s before next beacon */
        HAL_Delay(60000);

    /* USER CODE END WHILE */
    /* USER CODE BEGIN 3 */
    }
    /* USER CODE END 3 */
}

/* =========================================================
 * System Clock Configuration
 * 48 MHz from HSI48, used for CPU, AHB, APB1, USB
 * TIM6 @ 48 MHz / (PSC+1) / (ARR+1) = 48e6 / 25 / 100 = 19200 Hz ✓
 * ========================================================= */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
    RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_HSI14 | RCC_OSCILLATORTYPE_HSI48;
    RCC_OscInitStruct.HSI48State          = RCC_HSI48_ON;
    RCC_OscInitStruct.HSI14State          = RCC_HSI14_ON;
    RCC_OscInitStruct.HSI14CalibrationValue = 16;
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_NONE;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) { Error_Handler(); }

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_HSI48;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK) { Error_Handler(); }

    PeriphClkInit.PeriphClockSelection  = RCC_PERIPHCLK_USB | RCC_PERIPHCLK_USART1;
    PeriphClkInit.Usart1ClockSelection  = RCC_USART1CLKSOURCE_PCLK1;
    PeriphClkInit.UsbClockSelection     = RCC_USBCLKSOURCE_HSI48;
    if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * ADC Initialization
 * ========================================================= */
static void MX_ADC_Init(void)
{
    ADC_ChannelConfTypeDef sConfig = {0};

    hadc.Instance                   = ADC1;
    hadc.Init.ClockPrescaler        = ADC_CLOCK_ASYNC_DIV1;
    hadc.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc.Init.ScanConvMode          = ADC_SCAN_DIRECTION_FORWARD;
    hadc.Init.EOCSelection          = ADC_EOC_SINGLE_CONV;
    hadc.Init.LowPowerAutoWait      = DISABLE;
    hadc.Init.LowPowerAutoPowerOff  = DISABLE;
    hadc.Init.ContinuousConvMode    = DISABLE;
    hadc.Init.DiscontinuousConvMode = DISABLE;
    hadc.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc.Init.DMAContinuousRequests = DISABLE;
    hadc.Init.Overrun               = ADC_OVR_DATA_PRESERVED;
    if (HAL_ADC_Init(&hadc) != HAL_OK) { Error_Handler(); }

    sConfig.Channel      = ADC_CHANNEL_7;
    sConfig.Rank         = ADC_RANK_CHANNEL_NUMBER;
    sConfig.SamplingTime = ADC_SAMPLETIME_1CYCLE_5;
    if (HAL_ADC_ConfigChannel(&hadc, &sConfig) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * DAC Initialization
 * ========================================================= */
static void MX_DAC_Init(void)
{
    DAC_ChannelConfTypeDef sConfig = {0};

    hdac.Instance = DAC;
    if (HAL_DAC_Init(&hdac) != HAL_OK) { Error_Handler(); }

    sConfig.DAC_Trigger      = DAC_TRIGGER_T6_TRGO;
    sConfig.DAC_OutputBuffer = DAC_OUTPUTBUFFER_ENABLE;
    if (HAL_DAC_ConfigChannel(&hdac, &sConfig, DAC_CHANNEL_1) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * TIM6 Initialization
 * 48 MHz / (PSC+1=25) / (ARR+1=100) = 19200 Hz sample clock
 * ========================================================= */
static void MX_TIM6_Init(void)
{
    TIM_MasterConfigTypeDef sMasterConfig = {0};

    htim6.Instance               = TIM6;
    htim6.Init.Prescaler         = 24;   /* PSC+1 = 25 */
    htim6.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim6.Init.Period            = 99;   /* ARR+1 = 100 */
    htim6.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
    if (HAL_TIM_Base_Init(&htim6) != HAL_OK) { Error_Handler(); }

    sMasterConfig.MasterOutputTrigger = TIM_TRGO_UPDATE;
    sMasterConfig.MasterSlaveMode     = TIM_MASTERSLAVEMODE_DISABLE;
    if (HAL_TIMEx_MasterConfigSynchronization(&htim6, &sMasterConfig) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * USART1 Initialization — 9600 8N1 for radio module
 * ========================================================= */
static void MX_USART1_UART_Init(void)
{
    huart1.Instance            = USART1;
    huart1.Init.BaudRate       = 9600;
    huart1.Init.WordLength     = UART_WORDLENGTH_8B;
    huart1.Init.StopBits       = UART_STOPBITS_1;
    huart1.Init.Parity         = UART_PARITY_NONE;
    huart1.Init.Mode           = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl      = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling   = UART_OVERSAMPLING_16;
    huart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    if (HAL_UART_Init(&huart1) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * USB Initialization
 * ========================================================= */
static void MX_USB_PCD_Init(void)
{
    hpcd_USB_FS.Instance                  = USB;
    hpcd_USB_FS.Init.dev_endpoints        = 8;
    hpcd_USB_FS.Init.speed                = PCD_SPEED_FULL;
    hpcd_USB_FS.Init.phy_itface           = PCD_PHY_EMBEDDED;
    hpcd_USB_FS.Init.low_power_enable     = DISABLE;
    hpcd_USB_FS.Init.lpm_enable           = DISABLE;
    hpcd_USB_FS.Init.battery_charging_enable = DISABLE;
    if (HAL_PCD_Init(&hpcd_USB_FS) != HAL_OK) { Error_Handler(); }
}

/* =========================================================
 * DMA Initialization
 * ========================================================= */
static void MX_DMA_Init(void)
{
    __HAL_RCC_DMA1_CLK_ENABLE();
    HAL_NVIC_SetPriority(DMA1_Channel2_3_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(DMA1_Channel2_3_IRQn);
}

/* =========================================================
 * GPIO Initialization
 * PB2 = PTT (active LOW), PB3 = spare output
 * Both initialised HIGH (PTT de-asserted)
 * ========================================================= */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2 | GPIO_PIN_3, GPIO_PIN_SET);

    GPIO_InitStruct.Pin   = GPIO_PIN_2 | GPIO_PIN_3;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
}

/* =========================================================
 * Error Handler
 * ========================================================= */
void Error_Handler(void)
{
    __disable_irq();
    while (1) { }
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file; (void)line;
}
#endif
